csv:
  resource: "classpath:export_company2.csv"
spring:
  datasource:
    continue-on-error: true
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/kenan_monitor
    username: root
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8903